/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InstiShop } from "./InstiShop";
export * as factories from "./factories";
export { InstiShop__factory } from "./factories/InstiShop__factory";
